/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paintbasico;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import paintbasico.Lienzo.Herramienta;

/**
 *
 * @author adri
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private boolean barraEstadoActiva = true;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(800, 800);
        this.setTitle("Paint Basico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        herramientas = new javax.swing.ButtonGroup();
        colores = new javax.swing.ButtonGroup();
        barraHerramientas = new javax.swing.JToolBar();
        botonTrazoLibre = new javax.swing.JToggleButton();
        botonLinea = new javax.swing.JToggleButton();
        botonRectangulo = new javax.swing.JToggleButton();
        botonElipse = new javax.swing.JToggleButton();
        botonCurva = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        barraAtributos = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        colorNegro = new javax.swing.JToggleButton();
        colorRojo = new javax.swing.JToggleButton();
        colorAzul = new javax.swing.JToggleButton();
        colorNaranja = new javax.swing.JToggleButton();
        colorAmarillo = new javax.swing.JToggleButton();
        colorVerde = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jSpinner2 = new javax.swing.JSpinner();
        relleno = new javax.swing.JCheckBox();
        transparencia = new javax.swing.JCheckBox();
        alisar = new javax.swing.JCheckBox();
        mover = new javax.swing.JCheckBox();
        labelEstado = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuVerBarraEstado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraHerramientas.setRollover(true);

        herramientas.add(botonTrazoLibre);
        botonTrazoLibre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trazo.png"))); // NOI18N
        botonTrazoLibre.setSelected(true);
        botonTrazoLibre.setFocusable(false);
        botonTrazoLibre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTrazoLibre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonTrazoLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTrazoLibreActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonTrazoLibre);

        herramientas.add(botonLinea);
        botonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        botonLinea.setFocusable(false);
        botonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLineaActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonLinea);

        herramientas.add(botonRectangulo);
        botonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rectangulo.png"))); // NOI18N
        botonRectangulo.setFocusable(false);
        botonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRectanguloActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonRectangulo);

        herramientas.add(botonElipse);
        botonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipse.png"))); // NOI18N
        botonElipse.setFocusable(false);
        botonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElipseActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonElipse);

        herramientas.add(botonCurva);
        botonCurva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/curva.png"))); // NOI18N
        botonCurva.setFocusable(false);
        botonCurva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCurva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraHerramientas.add(botonCurva);

        getContentPane().add(barraHerramientas, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.BorderLayout());

        barraAtributos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barraAtributos.setRollover(true);

        colorNegro.setBackground(java.awt.Color.black);
        colores.add(colorNegro);
        colorNegro.setText(" ");
        colorNegro.setFocusable(false);
        colorNegro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorNegro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(colorNegro);

        colorRojo.setBackground(java.awt.Color.red);
        colores.add(colorRojo);
        colorRojo.setText(" ");
        colorRojo.setFocusable(false);
        colorRojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorRojo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(colorRojo);

        colorAzul.setBackground(java.awt.Color.blue);
        colores.add(colorAzul);
        colorAzul.setText(" ");
        colorAzul.setFocusable(false);
        colorAzul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorAzul.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(colorAzul);

        colorNaranja.setBackground(java.awt.Color.orange);
        colores.add(colorNaranja);
        colorNaranja.setText(" ");
        colorNaranja.setFocusable(false);
        colorNaranja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorNaranja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(colorNaranja);

        colorAmarillo.setBackground(java.awt.Color.yellow);
        colores.add(colorAmarillo);
        colorAmarillo.setText(" ");
        colorAmarillo.setFocusable(false);
        colorAmarillo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorAmarillo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(colorAmarillo);

        colorVerde.setBackground(java.awt.Color.green);
        colores.add(colorVerde);
        colorVerde.setText(" ");
        colorVerde.setFocusable(false);
        colorVerde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorVerde.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(colorVerde);

        barraAtributos.add(jPanel1);

        jPanel2.add(jSpinner2);

        relleno.setText("Relleno");
        jPanel2.add(relleno);

        transparencia.setText("Transparencia");
        jPanel2.add(transparencia);

        alisar.setText("Alisar");
        jPanel2.add(alisar);

        mover.setText("Mover");
        jPanel2.add(mover);

        barraAtributos.add(jPanel2);

        jPanel6.add(barraAtributos, java.awt.BorderLayout.PAGE_START);

        labelEstado.setText("Barra de estado");
        jPanel6.add(labelEstado, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("File");

        menuNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuNuevo.setText("Nuevo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuNuevo);

        menuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuAbrir);

        menuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuGuardar);

        barraMenu.add(menuArchivo);

        menuEdicion.setText("Edit");

        menuVerBarraEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuVerBarraEstado.setText("Ver barra de estado");
        menuVerBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerBarraEstadoActionPerformed(evt);
            }
        });
        menuEdicion.add(menuVerBarraEstado);

        barraMenu.add(menuEdicion);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTrazoLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTrazoLibreActionPerformed
        lienzo.setHerramienta(Herramienta.TRAZO_LIBRE);
        if(barraEstadoActiva)
            labelEstado.setText("Punto");
    }//GEN-LAST:event_botonTrazoLibreActionPerformed

    private void botonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLineaActionPerformed
        lienzo.setHerramienta(Herramienta.LINEA);
        if(barraEstadoActiva)
            labelEstado.setText("Linea");
    }//GEN-LAST:event_botonLineaActionPerformed

    private void botonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRectanguloActionPerformed
        lienzo.setHerramienta(Herramienta.RECTANGULO);
        if(barraEstadoActiva)
            labelEstado.setText("Rectangulo");
    }//GEN-LAST:event_botonRectanguloActionPerformed

    private void botonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElipseActionPerformed
        lienzo.setHerramienta(Herramienta.ELIPSE);
        if(barraEstadoActiva)
            labelEstado.setText("Eclipse");
    }//GEN-LAST:event_botonElipseActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        lienzo.setBlank();
        lienzo.repaint();
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuVerBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerBarraEstadoActionPerformed
        barraEstadoActiva = !barraEstadoActiva;
        labelEstado.setText(" ");
    }//GEN-LAST:event_menuVerBarraEstadoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alisar;
    private javax.swing.JToolBar barraAtributos;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JToggleButton botonCurva;
    private javax.swing.JToggleButton botonElipse;
    private javax.swing.JToggleButton botonLinea;
    private javax.swing.JToggleButton botonRectangulo;
    private javax.swing.JToggleButton botonTrazoLibre;
    private javax.swing.JToggleButton colorAmarillo;
    private javax.swing.JToggleButton colorAzul;
    private javax.swing.JToggleButton colorNaranja;
    private javax.swing.JToggleButton colorNegro;
    private javax.swing.JToggleButton colorRojo;
    private javax.swing.JToggleButton colorVerde;
    private javax.swing.ButtonGroup colores;
    private javax.swing.ButtonGroup herramientas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenuItem menuVerBarraEstado;
    private javax.swing.JCheckBox mover;
    private javax.swing.JCheckBox relleno;
    private javax.swing.JCheckBox transparencia;
    // End of variables declaration//GEN-END:variables
}
