/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sm.aas.comboboxcolores;

import java.awt.Color;

/**
 *
 * @author adrian
 */
public class PanelColor extends javax.swing.JPanel {

    /**
     * Creates new form PanelColor
     */
    public PanelColor(Color color) {
        initComponents();
        bColor.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bColor = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        bColor.setText(" ");
        add(bColor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void setColor(Color color){
        bColor.setBackground(color);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bColor;
    // End of variables declaration//GEN-END:variables
}
